driver:
  name: vagrant
  provider: vmware_fusion
  memory: 2048
  cpus: 2

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.8.0
  data_path: test/shared

platforms:
  - name: ubuntu-13.04
    driver:
      box: opscode-ubuntu-13.04

suites:
  #
  # Command suites
  #
  - name: jenkins_command_execute
    run_list: jenkins_command::execute

  #
  # Job suites
  #
  - name: jenkins_job_create
    run_list: jenkins_job::create
  - name: jenkins_job_delete
    run_list: jenkins_job::delete
  - name: jenkins_job_disable
    run_list: jenkins_job::disable
  - name: jenkins_job_enable
    run_list: jenkins_job::enable

  - name: plugin
    run_list: jenkins_test::plugin

  #
  # User suites
  #
  - name: jenkins_user_create
    run_list: jenkins_user::create
  - name: jenkins_user_delete
    run_list: jenkins_user::delete
