driver:
  name: vagrant
  provider: vmware_fusion
  memory: 2048
  cpus: 2

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.8.0

platforms:
  - name: ubuntu-13.04
    driver:
      box: opscode-ubuntu-13.04

suites:
  - name: job
    run_list: jenkins_test::job
  - name: plugin
    run_list: jenkins_test::plugin
